// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybWvr6AT5c3GzS-bYoWGJJsixvWQ4aiE',
    appId: '1:205341726925:web:05af8fb298eead3325b184',
    messagingSenderId: '205341726925',
    projectId: 'thecoldbox-2',
    authDomain: 'thecoldbox-2.firebaseapp.com',
    storageBucket: 'thecoldbox-2.appspot.com',
    measurementId: 'G-BEVVK2P9NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw1agJy0VBwj3OhDBM0Hpk2o46DBU8iGM',
    appId: '1:205341726925:android:fc6e345973e8294025b184',
    messagingSenderId: '205341726925',
    projectId: 'thecoldbox-2',
    storageBucket: 'thecoldbox-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxj1jT5a3y5AdPLLscrsDwMPe-0FSV2A',
    appId: '1:205341726925:ios:7ea1a30d87fbbdbb25b184',
    messagingSenderId: '205341726925',
    projectId: 'thecoldbox-2',
    storageBucket: 'thecoldbox-2.appspot.com',
    iosBundleId: 'com.example.thecoldbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhxj1jT5a3y5AdPLLscrsDwMPe-0FSV2A',
    appId: '1:205341726925:ios:0c908ca97d5a4d3b25b184',
    messagingSenderId: '205341726925',
    projectId: 'thecoldbox-2',
    storageBucket: 'thecoldbox-2.appspot.com',
    iosBundleId: 'com.example.thecoldbox.RunnerTests',
  );
}
